// Scaffold placeholder xUnit test class generated by the .NET template; contains an empty passing test.
namespace AeroMetrix.API.Tests;

public class UnitTest1
{
    [Fact]
    public void Test1()
    {

    }
}