// Scaffold placeholder model representing a weather forecast entry; generated by the .NET template and not used in production.
namespace AeroMetrix.API;

public class WeatherForecast
{
    public DateOnly Date { get; set; }

    public int TemperatureC { get; set; }

    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);

    public string? Summary { get; set; }
}
