// <auto-generated />
using System;
using AeroMetrix.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroMetrix.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.18");

            modelBuilder.Entity("AeroMetrix.API.Models.DroneConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DroneModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EmptyWeightKg")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxBatteryCapacityMAh")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DroneConfigurations");
                });

            modelBuilder.Entity("AeroMetrix.API.Models.FlightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgWindResistanceMs")
                        .HasColumnType("REAL");

                    b.Property<double>("BatteryDrainRateMAhPerMin")
                        .HasColumnType("REAL");

                    b.Property<int>("DroneConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DroneConfigurationId");

                    b.ToTable("FlightLogs");
                });

            modelBuilder.Entity("AeroMetrix.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AeroMetrix.API.Models.FlightLog", b =>
                {
                    b.HasOne("AeroMetrix.API.Models.DroneConfiguration", "DroneConfiguration")
                        .WithMany()
                        .HasForeignKey("DroneConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DroneConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
